---
- hosts: localhost
  connection: local
  tasks:
    - name: set directory fact
      set_fact:
        kenv_dir: ~/.kube/env-{{ lookup('env', 'kenv') }}
    - name: clear existing directory
      file:
        path: '{{ kenv_dir }}'
        state: absent
    - name: make directory for kenv
      file:
        path: '{{ kenv_dir }}'
        state: directory

- hosts: kube-master[0]
  become: yes
  gather_facts: no
  tasks:
    - set_fact:
        ansible_python_interpreter: "/opt/bin/python"
      when: bootstrap_os == "coreos"
    - name: gather facts
      setup:
    - name: set directory fact
      set_fact:
        kenv_dir: '{{ hostvars["localhost"]["kenv_dir"] }}'
    - name: sync
      synchronize:
        mode: pull
        src: /etc/kubernetes/node-kubeconfig.yaml
        dest: '{{ kenv_dir }}/config'
    - name: sync
      synchronize:
        mode: pull
        src: /etc/kubernetes/ssl
        dest: '{{ kenv_dir }}/'
      register: sync_done

- hosts: localhost
  connection: local
  tasks:
    - name: replace host
      replace:
        path: '{{ kenv_dir }}/config'
        regexp: 'server: .*'
        replace: 'server: https://{{ apiserver_loadbalancer_domain_name }}'
    - name: replace keys
      replace:
        path: '{{ kenv_dir }}/config'
        regexp: /etc/kubernetes/
