# Valid bootstrap options (required): ubuntu, coreos, centos, none
bootstrap_os: none

#Directory where etcd data stored
etcd_data_dir: /var/lib/etcd

# Directory where the binaries will be installed
bin_dir: /usr/local/bin

## External LB example config
apiserver_loadbalancer_domain_name: changeme
loadbalancer_apiserver:
  address: changeme
  port: 443

# Versions
docker_version: "1.13"
kube_version: "v1.8.2"
kubeadm_version: "{{ kube_version }}"
etcd_version: "v3.2.6"
calico_version: "v2.5.0"
calico_ctl_version: "v1.5.0"
calico_cni_version: "v1.10.0"
calico_policy_version: "v0.7.0"
calico_rr_version: "v0.4.0"
weave_version: "2.0.4"
flannel_version: "v0.9.0"
flannel_cni_version: "v0.3.0"
pod_infra_version: "3.0"
netcheck_version: "v1.0"
dnsmasq_version: "2.78"
kubedns_version: "1.14.7"
kubednsautoscaler_version: "1.1.1"
elasticsearch_version: "v2.4.1"
fluentd_version: "1.22"
kibana_version: "v4.6.1"
helm_version: "v2.2.2"
vault_version: "0.8.1"
istio_version: "0.2.6"
dashboard_version: "v1.6.3"

registry_prefix: registry.cn-hangzhou.aliyuncs.com/crstudio

# Containers
etcd_image_repo: "{{ registry_prefix }}/etcd"
etcd_image_tag: "{{ etcd_version }}"
hyperkube_image_repo: "{{ registry_prefix }}/hyperkube-amd64"
hyperkube_image_tag: "{{ kube_version }}"
pod_infra_image_repo: "{{ registry_prefix }}/pause-amd64"
pod_infra_image_tag: "{{ pod_infra_version }}"
kubedns_image_repo: "{{ registry_prefix }}/k8s-dns-kube-dns-amd64"
kubedns_image_tag: "{{ kubedns_version }}"
dnsmasq_image_repo: "andyshinn/dnsmasq"
dnsmasq_image_tag: "{{ dnsmasq_version }}"
dnsmasq_nanny_image_repo: "{{ registry_prefix }}/k8s-dns-dnsmasq-nanny-amd64"
dnsmasq_nanny_image_tag: "{{ kubedns_version }}"
dnsmasq_sidecar_image_repo: "{{ registry_prefix }}/k8s-dns-sidecar-amd64"
dnsmasq_sidecar_image_tag: "{{ kubedns_version }}"
kubednsautoscaler_image_repo: "{{ registry_prefix }}/cluster-proportional-autoscaler-amd64"
kubednsautoscaler_image_tag: "{{ kubednsautoscaler_version }}"
install_socat_image_repo: "xueshanf/install-socat"
install_socat_image_tag: "latest"
vault_image_repo: "vault"
vault_image_tag: "{{ vault_version }}"

# network plugins
flannel_image_repo: "{{ registry_prefix }}/flannel"
flannel_image_tag: "{{ flannel_version }}"
flannel_cni_image_repo: "{{ registry_prefix }}/flannel-cni"
flannel_cni_image_tag: "{{ flannel_cni_version }}"
calicoctl_image_repo: "calico/ctl"
calicoctl_image_tag: "{{ calico_ctl_version }}"
calico_node_image_repo: "calico/node"
calico_node_image_tag: "{{ calico_version }}"
calico_cni_image_repo: "calico/cni"
calico_cni_image_tag: "{{ calico_cni_version }}"
calico_policy_image_repo: "calico/kube-policy-controller"
calico_policy_image_tag: "{{ calico_policy_version }}"
calico_rr_image_repo: "calico/routereflector"
calico_rr_image_tag: "{{ calico_rr_version }}"
weave_kube_image_repo: "weaveworks/weave-kube"
weave_kube_image_tag: "{{ weave_version }}"
weave_npc_image_repo: "weaveworks/weave-npc"
weave_npc_image_tag: "{{ weave_version }}"
netcheck_agent_image_repo: "{{ registry_prefix }}/k8s-netchecker-agent"
netcheck_agent_image_tag: "{{ netcheck_version }}"
netcheck_server_image_repo: "{{ registry_prefix }}/k8s-netchecker-server"
netcheck_server_image_tag: "{{ netcheck_version }}"
dashboard_image_repo: "{{ registry_prefix }}/kubernetes-dashboard-amd64"
dashboard_image_tag: "{{ dashboard_version }}"

elasticsearch_image_repo: "{{ registry_prefix }}/elasticsearch"
elasticsearch_image_tag: "{{ elasticsearch_version }}"
fluentd_image_repo: "{{ registry_prefix }}/fluentd-elasticsearch"
fluentd_image_tag: "{{ fluentd_version }}"
kibana_image_repo: "{{ registry_prefix }}/kibana"
kibana_image_tag: "{{ kibana_version }}"

helm_image_repo: "lachlanevenson/k8s-helm"
helm_image_tag: "{{ helm_version }}"
tiller_image_repo: "{{ registry_prefix }}/tiller"
tiller_image_tag: "{{ helm_version }}"

nginx_image_repo: nginx
nginx_image_tag: 1.11.4-alpine

test_image_repo: busybox
test_image_tag: latest

# Download URLs
etcd_download_url: "https://storage.googleapis.com/etcd/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
etcd_checksum: "5077b02b255d019fb070749ad2ab4fce117a6cd575fe28fe6038edd8090d818d"
vault_download_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
vault_binary_checksum: "3c4d70ba71619a43229e65c67830e30e050eab7a81ac6b28325ff707e5914188"
kubeadm_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubeadm_version }}/bin/linux/amd64/kubeadm"
kubeadm_checksum: "ea1c53b88e6e562c9c0ae4f523b56fa7f83850c4894f619a24c069e0130f417d"
istioctl_download_url: "https://storage.googleapis.com/istio-release/releases/{{ istio_version }}/istioctl/istioctl-linux"
istioctl_checksum: "fd703063c540b8c0ab943f478c05ab257d88ae27224c746a27d0526ddbf7c370"
